# Site settings
title: School for Poetic Computation
email: paigederaedt@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Reflections on my time at the School for Poetic Computation during Fall 2014.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://paigederaedt.github.io" # the base hostname & protocol for your site
twitter_username: paigederaedt
github_username:  paigederaedt

# Build settings
markdown: kramdown
